In [2]:
from modules.get_data_table import get_base_data
data = get_base_data()
data.head()

,item_id,year,month,seq,type,hs4,weight,quantity,value,quantity_weight,unit_value,value_per_weight,value_per_quantity,hs4_encoded,ym,ym_seq
0,DEWLVASR,2022,1,1.0,1,3038,14858.0,0.0,32688.0,14858.0,2.200027,2.200027,0.0,2.982368,2022-01-01,2022-01-01
1,ELQGMQWE,2022,1,1.0,1,2002,62195.0,0.0,110617.0,62195.0,1.778551,1.778551,0.0,2.712733,2022-01-01,2022-01-01
2,AHMDUILJ,2022,1,1.0,1,2102,18426.0,0.0,72766.0,18426.0,3.949094,3.949094,0.0,6.462845,2022-01-01,2022-01-01
3,XIPPENFQ,2022,1,1.0,1,2501,20426.0,0.0,11172.0,20426.0,0.546950,0.546950,0.0,0.783339,2022-01-01,2022-01-01
4,FTSVTTSR,2022,1,1.0,1,2529,248000.0,0.0,143004.0,248000.0,0.576629,0.576629,0.0,0.583389,2022-01-01,2022-01-01

In [3]:

from modules.get_data_table import VALUE_PIVOUT, QUANTITY_WEIGHT_PIVOUT
value_pivot = VALUE_PIVOUT(data)
weight_quantity_pivot= QUANTITY_WEIGHT_PIVOUT(data)

value_pivot.head()

,ym,2022-01-01,2022-02-01,2022-03-01,2022-04-01,2022-05-01,2022-06-01,2022-07-01,2022-08-01,2022-09-01,2022-10-01,...,2024-10-01,2024-11-01,2024-12-01,2025-01-01,2025-02-01,2025-03-01,2025-04-01,2025-05-01,2025-06-01,2025-07-01
item_id,hs4,,,,,,,,,,,,,,,,,,,,,
AANGBULD,4810,14276.0,52347.0,53549.0,0.0,26997.0,84489.0,0.0,0.0,0.0,0.0,...,428725.0,144248.0,26507.0,25691.0,25805.0,0.0,38441.0,0.0,441275.0,533478.0
AHMDUILJ,2102,242705.0,120847.0,197317.0,126142.0,71730.0,149138.0,186617.0,169995.0,140547.0,89292.0,...,123085.0,143451.0,78649.0,125098.0,80404.0,157401.0,115509.0,127473.0,89479.0,101317.0
ANWUJOKX,4403,0.0,0.0,0.0,63580.0,81670.0,26424.0,8470.0,0.0,0.0,80475.0,...,0.0,0.0,0.0,27980.0,0.0,0.0,0.0,0.0,0.0,0.0
APQGTRMF,8105,383999.0,512813.0,217064.0,470398.0,539873.0,582317.0,759980.0,216019.0,537693.0,205326.0,...,683581.0,2147.0,0.0,25013.0,77.0,20741.0,2403.0,3543.0,32430.0,40608.0
ATLDMDBO,2814,143097177.0,103568323.0,118403737.0,121873741.0,115024617.0,65716075.0,146216818.0,97552978.0,72341427.0,87454167.0,...,60276050.0,30160198.0,42613728.0,64451013.0,38667429.0,29354408.0,42450439.0,37136720.0,32181798.0,57090235.0

In [4]:
import pandas as pd
# train_pairs = pd.read_csv("./datas/train_pairs_12_12_0.4.csv")
# test_pairs = pd.read_csv("./datas/predict_pairs_12_12_0.4.csv")
temp_pairs = pd.read_csv("./datas/comovement_pairs.csv")

In [4]:
from modules.create_features import create_train_set

# 테스트용 feature에는 7월 데이터 불 포함
test_value_pivot = value_pivot.drop(columns=[pd.to_datetime("2025-07-01")])
test_weight_quantity_pivot = weight_quantity_pivot.drop(columns=[pd.to_datetime("2025-07-01")])

In [ ]:
from sklearn.model_selection import GroupShuffleSplit
X_test, y_test = pd.read_csv("./datas/X_test.csv"), pd.read_csv("./datas/y_test.csv")

#그룹 기준
groups = X_test['선행품목hs4_encoded']

gss = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=42)
train_idx, valid_idx = next(gss.split(X_test, y_test, groups=groups))

X_train = X_test.iloc[train_idx]
y_train = y_test.iloc[train_idx]
X_valid = X_test.iloc[valid_idx]
y_valid = y_test.iloc[valid_idx]

X_train.to_csv("./datas/X_train.csv", index=False)
y_train.to_csv("./datas/y_train.csv", index=False)
X_valid.to_csv("./datas/X_valid.csv", index=False)
y_valid.to_csv("./datas/y_valid.csv", index=False)

Train set: 29125 samples
Valid set: 6241 samples