In [1]:
import pandas as pd

In [2]:
from modules.get_data_table import get_base_data
data = get_base_data()

In [3]:
MAX_LAG = 12
CORR_THRESHOLD = 0.3

In [4]:
from modules.get_data_table import VALUE_PIVOUT

value_pivot = VALUE_PIVOUT(data)
value_pivot

,ym,2022-01-01,2022-02-01,2022-03-01,2022-04-01,2022-05-01,2022-06-01,2022-07-01,2022-08-01,2022-09-01,2022-10-01,...,2024-10-01,2024-11-01,2024-12-01,2025-01-01,2025-02-01,2025-03-01,2025-04-01,2025-05-01,2025-06-01,2025-07-01
item_id,hs4,,,,,,,,,,,,,,,,,,,,,
AANGBULD,4810,14276.0,52347.0,53549.0,0.0,26997.0,84489.0,0.0,0.0,0.0,0.0,...,428725.0,144248.0,26507.0,25691.0,25805.0,0.0,38441.0,0.0,441275.0,533478.0
AHMDUILJ,2102,242705.0,120847.0,197317.0,126142.0,71730.0,149138.0,186617.0,169995.0,140547.0,89292.0,...,123085.0,143451.0,78649.0,125098.0,80404.0,157401.0,115509.0,127473.0,89479.0,101317.0
ANWUJOKX,4403,0.0,0.0,0.0,63580.0,81670.0,26424.0,8470.0,0.0,0.0,80475.0,...,0.0,0.0,0.0,27980.0,0.0,0.0,0.0,0.0,0.0,0.0
APQGTRMF,8105,383999.0,512813.0,217064.0,470398.0,539873.0,582317.0,759980.0,216019.0,537693.0,205326.0,...,683581.0,2147.0,0.0,25013.0,77.0,20741.0,2403.0,3543.0,32430.0,40608.0
ATLDMDBO,2814,143097177.0,103568323.0,118403737.0,121873741.0,115024617.0,65716075.0,146216818.0,97552978.0,72341427.0,87454167.0,...,60276050.0,30160198.0,42613728.0,64451013.0,38667429.0,29354408.0,42450439.0,37136720.0,32181798.0,57090235.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YSYHGLQK,2807,0.0,543.0,766.0,1108.0,859.0,1426.0,2413.0,638.0,0.0,1199.0,...,188.0,541.0,696.0,8710.0,3175.0,2624.0,0.0,182.0,2128.0,10651.0
ZCELVYQU,8461,373859.0,59900.0,31158.0,594407.0,648232.0,496737.0,210179.0,0.0,70748.0,15512.0,...,0.0,609803.0,23712.0,654630.0,4496.0,1177300.0,1187539.0,26434.0,115631.0,270262.0
ZGJXVMNI,3006,1154724.0,1337622.0,1662893.0,1561647.0,1603223.0,1641942.0,1815161.0,1546959.0,1536799.0,1496906.0,...,3168505.0,3059865.0,1579976.0,1413293.0,3038078.0,2915914.0,3565526.0,3020051.0,2412781.0,2458481.0
ZKENOUDA,2805,122627.0,38162.0,3592.0,5613.0,33924.0,74939.0,93976.0,83364.0,53842.0,8591.0,...,337908.0,331182.0,291075.0,83785.0,487156.0,319283.0,443958.0,329906.0,461599.0,327761.0
ZXERAXWP,4802,10867.0,675.0,20548.0,662.0,18949.0,4566.0,12358.0,5108.0,7954.0,6420.0,...,5458.0,12922.0,17825.0,19599.0,12279.0,12817.0,12482.0,18224.0,42690.0,20678.0

In [ ]:
from modules.differencing import log_difference_transform
preprocessed_pivot = log_difference_transform(value_pivot)
preprocessed_pivot

ym             2022-02-01  2022-03-01  2022-04-01  2022-05-01  2022-06-01  \
item_id  hs4
AANGBULD 4810    1.299264    0.022702  -10.888371   10.203518    1.140870
AHMDUILJ 2102   -0.697317    0.490283   -0.447400   -0.564493    0.731956
ANWUJOKX 4403    0.000000    0.000000   11.060070    0.250384   -1.128388
APQGTRMF 8105    0.289271   -0.859716    0.773384    0.137755    0.075681
ATLDMDBO 2814   -0.323292    0.133869    0.028885   -0.057839   -0.559803

ym             2022-07-01  2022-08-01  2022-09-01  2022-10-01  2022-11-01  \
item_id  hs4
AANGBULD 4810  -11.344388    0.000000    0.000000    0.000000    5.703782
AHMDUILJ 2102    0.224185   -0.093289   -0.190226   -0.453626    0.458714
ANWUJOKX 4403   -1.137662   -9.044404    0.000000   11.295714  -11.295714
APQGTRMF 8105    0.266277   -1.257922    0.911919   -0.962686   -0.192099
ATLDMDBO 2814    0.799747   -0.404695   -0.298999    0.189718   -0.363088

ym             ...  2024-10-01  2024-11-01  2024-12-01  2025-01-01  \
item_id  hs4   ...
AANGBULD 4810  ...    0.314369   -1.089277   -1.694094   -0.031267
AHMDUILJ 2102  ...   -0.407045    0.153117   -0.600993    0.464098
ANWUJOKX 4403  ...    0.000000    0.000000    0.000000   10.239281
APQGTRMF 8105  ...    2.026360   -5.762809   -7.672292   10.127191
ATLDMDBO 2814  ...    0.721622   -0.692412    0.345653    0.413729

ym             2025-02-01  2025-03-01  2025-04-01  2025-05-01  2025-06-01  \
item_id  hs4
AANGBULD 4810    0.004427  -10.158362   10.556906  -10.556906   12.997426
AHMDUILJ 2102   -0.442029    0.671727   -0.309446    0.098555   -0.353897
ANWUJOKX 4403  -10.239281    0.000000    0.000000    0.000000    0.000000
APQGTRMF 8105   -5.770482    5.583207   -2.155027    0.388122    2.213859
ATLDMDBO 2814   -0.510908   -0.275555    0.368895   -0.133731   -0.143205

ym             2025-07-01
item_id  hs4
AANGBULD 4810    0.189749
AHMDUILJ 2102    0.124249
ANWUJOKX 4403    0.000000
APQGTRMF 8105    0.224875
ATLDMDBO 2814    0.573232

[5 rows x 42 columns]

,ym,2022-02-01,2022-03-01,2022-04-01,2022-05-01,2022-06-01,2022-07-01,2022-08-01,2022-09-01,2022-10-01,2022-11-01,...,2024-10-01,2024-11-01,2024-12-01,2025-01-01,2025-02-01,2025-03-01,2025-04-01,2025-05-01,2025-06-01,2025-07-01
item_id,hs4,,,,,,,,,,,,,,,,,,,,,
AANGBULD,4810,1.299264,0.022702,-10.888371,10.203518,1.140870,-11.344388,0.000000,0.000000,0.000000,5.703782,...,0.314369,-1.089277,-1.694094,-0.031267,0.004427,-10.158362,10.556906,-10.556906,12.997426,0.189749
AHMDUILJ,2102,-0.697317,0.490283,-0.447400,-0.564493,0.731956,0.224185,-0.093289,-0.190226,-0.453626,0.458714,...,-0.407045,0.153117,-0.600993,0.464098,-0.442029,0.671727,-0.309446,0.098555,-0.353897,0.124249
ANWUJOKX,4403,0.000000,0.000000,11.060070,0.250384,-1.128388,-1.137662,-9.044404,0.000000,11.295714,-11.295714,...,0.000000,0.000000,0.000000,10.239281,-10.239281,0.000000,0.000000,0.000000,0.000000,0.000000
APQGTRMF,8105,0.289271,-0.859716,0.773384,0.137755,0.075681,0.266277,-1.257922,0.911919,-0.962686,-0.192099,...,2.026360,-5.762809,-7.672292,10.127191,-5.770482,5.583207,-2.155027,0.388122,2.213859,0.224875
ATLDMDBO,2814,-0.323292,0.133869,0.028885,-0.057839,-0.559803,0.799747,-0.404695,-0.298999,0.189718,-0.363088,...,0.721622,-0.692412,0.345653,0.413729,-0.510908,-0.275555,0.368895,-0.133731,-0.143205,0.573232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YSYHGLQK,2807,6.298949,0.343538,0.368727,-0.254282,0.506397,0.525711,-1.329136,-6.459904,7.090077,-0.108142,...,-0.711496,1.053519,0.251519,2.525556,-1.008964,-0.190542,-7.872836,5.209486,2.453922,1.610095
ZCELVYQU,8461,-1.831188,-0.653590,2.948463,0.086684,-0.266187,-0.860098,-12.255720,11.166894,-1.517460,2.957135,...,-11.328822,13.320893,-3.247114,3.318048,-4.980661,5.567569,0.008659,-3.804950,1.475724,0.848983
ZGJXVMNI,3006,0.147032,0.217665,-0.062818,0.026275,0.023864,0.100294,-0.159883,-0.006589,-0.026301,0.143042,...,-0.010972,-0.034889,-0.660961,-0.111487,0.765302,-0.041042,0.201128,-0.166038,-0.224494,0.018764
ZKENOUDA,2805,-1.167289,-2.362879,0.446276,1.798889,0.792536,0.226362,-0.119822,-0.437156,-1.835241,2.397461,...,-0.267082,-0.020106,-0.129087,-1.245318,1.760321,-0.422505,0.329651,-0.296921,0.335888,-0.342411
ZXERAXWP,4802,-2.777385,3.414374,-3.433793,3.352784,-1.422947,0.995528,-0.883381,0.442797,-0.214227,0.852003,...,-0.407844,0.861743,0.321649,0.094872,-0.467558,0.042879,-0.026483,0.378427,0.851194,-0.724869

In [ ]:
 import pandas as pd
    from get_data_table import VALUE_PIVOUT, get_base_data
    from sklearn.preprocessing import robust_scale

    
    pairs = pd.read_csv("./datas/comovement_pairs.csv")

    valid_pairs = get_final_validation(pairs, pivot, preprocessed_pivot)
    valid_pairs.to_csv("./datas/validated_linear_comovement_pairs.csv", index=False)
    print(valid_pairs.head())

In [5]:
from modules.find_comovement_pairs import get_comovement_pairs
feature = value_pivot.drop(columns=[pd.to_datetime("2025-07-01")])
target = value_pivot[pd.to_datetime("2025-07-01")]
train_pairs = get_comovement_pairs(
    feature, 
    max_lag=MAX_LAG,
    corr_threshold=CORR_THRESHOLD,
)

설정값:
- 상관계수 임계값: 0.4
- 최대 지연 기간: 12개월
- 최소 무역량 보유 개월수: 12개월

공행성 쌍 탐색: 100it [00:16,  6.20it/s]

📊 검정 결과:
- 총 발견된 공행성 쌍: 1988

In [ ]:
train_pairs.to_csv(f"./datas/train_pairs_{MAX_LAG}_{CORR_THRESHOLD}.csv", index=False)

In [ ]:
from modules.find_comovement_pairs import get_comovement_pairs
predict_pairs = get_comovement_pairs(
    value_pivot,
    max_lag=MAX_LAG,
    corr_threshold=CORR_THRESHOLD,
)

설정값:
- 상관계수 임계값: 0.4
- 최대 지연 기간: 12개월
- 최소 무역량 보유 개월수: 12개월

공행성 쌍 탐색: 100it [00:16,  6.21it/s]

📊 검정 결과:
- 총 발견된 공행성 쌍: 1487

In [ ]:
predict_pairs.to_csv(f"./datas/predict_pairs_{MAX_LAG}_{CORR_THRESHOLD}.csv", index=False)